// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(EnterpriseDBContext))]
    [Migration("20260112142724_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregate.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Domain.Aggregate.Enterprise", b =>
                {
                    b.Property<Guid>("EnterpriseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EnterpriseID");

                    b.HasIndex("TIN")
                        .IsUnique();

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("Domain.Aggregate.WasteType", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Type");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("WasteTypes");
                });

            modelBuilder.Entity("Domain.Entity.BonusRule", b =>
                {
                    b.Property<Guid>("PenaltyRuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BonusPoint")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RewardPolicyID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PenaltyRuleID");

                    b.HasIndex("RewardPolicyID");

                    b.ToTable("BonusRules");
                });

            modelBuilder.Entity("Domain.Entity.Capacity", b =>
                {
                    b.Property<Guid>("CapacityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentLoad")
                        .HasColumnType("float");

                    b.Property<Guid>("EnterpriseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("MaxDailyCapacity")
                        .HasColumnType("float");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitOfMeasure")
                        .HasColumnType("int");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CapacityID");

                    b.HasIndex("EnterpriseID", "WasteType");

                    b.ToTable("Capacities");
                });

            modelBuilder.Entity("Domain.Entity.CollectionAssignment", b =>
                {
                    b.Property<Guid>("CollectionAssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssigneeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapacityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollectionReportID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CollectionAssignmentID");

                    b.HasIndex("CapacityID");

                    b.ToTable("CollectionAssignments");
                });

            modelBuilder.Entity("Domain.Entity.Member", b =>
                {
                    b.Property<Guid>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EnterpriseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UnassignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MemberID");

                    b.HasIndex("EnterpriseID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Domain.Entity.PenaltyRule", b =>
                {
                    b.Property<Guid>("PenaltyRuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PenaltyPoint")
                        .HasColumnType("int");

                    b.Property<Guid>("RewardPolicyID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PenaltyRuleID");

                    b.HasIndex("RewardPolicyID");

                    b.ToTable("PenaltyRules");
                });

            modelBuilder.Entity("Domain.Entity.RewardPolicy", b =>
                {
                    b.Property<Guid>("RewardPolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BasePoint")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EnterpriseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RewardPolicyID");

                    b.HasIndex("EnterpriseID");

                    b.ToTable("RewardPolicies");
                });

            modelBuilder.Entity("Domain.Entity.BonusRule", b =>
                {
                    b.HasOne("Domain.Entity.RewardPolicy", null)
                        .WithMany("BonusRules")
                        .HasForeignKey("RewardPolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.Capacity", b =>
                {
                    b.HasOne("Domain.Aggregate.Enterprise", null)
                        .WithMany("Capacities")
                        .HasForeignKey("EnterpriseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.CollectionAssignment", b =>
                {
                    b.HasOne("Domain.Entity.Capacity", null)
                        .WithMany("CollectionAssignments")
                        .HasForeignKey("CapacityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.Member", b =>
                {
                    b.HasOne("Domain.Aggregate.Enterprise", null)
                        .WithMany("Members")
                        .HasForeignKey("EnterpriseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.PenaltyRule", b =>
                {
                    b.HasOne("Domain.Entity.RewardPolicy", null)
                        .WithMany("PenaltyRules")
                        .HasForeignKey("RewardPolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.RewardPolicy", b =>
                {
                    b.HasOne("Domain.Aggregate.Enterprise", null)
                        .WithMany("RewardPolicies")
                        .HasForeignKey("EnterpriseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregate.Enterprise", b =>
                {
                    b.Navigation("Capacities");

                    b.Navigation("Members");

                    b.Navigation("RewardPolicies");
                });

            modelBuilder.Entity("Domain.Entity.Capacity", b =>
                {
                    b.Navigation("CollectionAssignments");
                });

            modelBuilder.Entity("Domain.Entity.RewardPolicy", b =>
                {
                    b.Navigation("BonusRules");

                    b.Navigation("PenaltyRules");
                });
#pragma warning restore 612, 618
        }
    }
}
